package db.dao;

import db.model.ProductParams;
import db.model.ProductParamsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PARAMS
     *
     * @mbg.generated Wed Sep 08 16:48:37 MSK 2021
     */
    long countByExample(ProductParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PARAMS
     *
     * @mbg.generated Wed Sep 08 16:48:37 MSK 2021
     */
    int deleteByExample(ProductParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PARAMS
     *
     * @mbg.generated Wed Sep 08 16:48:37 MSK 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PARAMS
     *
     * @mbg.generated Wed Sep 08 16:48:37 MSK 2021
     */
    int insert(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PARAMS
     *
     * @mbg.generated Wed Sep 08 16:48:37 MSK 2021
     */
    int insertSelective(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PARAMS
     *
     * @mbg.generated Wed Sep 08 16:48:37 MSK 2021
     */
    List<ProductParams> selectByExample(ProductParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PARAMS
     *
     * @mbg.generated Wed Sep 08 16:48:37 MSK 2021
     */
    ProductParams selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PARAMS
     *
     * @mbg.generated Wed Sep 08 16:48:37 MSK 2021
     */
    int updateByExampleSelective(@Param("record") ProductParams record, @Param("example") ProductParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PARAMS
     *
     * @mbg.generated Wed Sep 08 16:48:37 MSK 2021
     */
    int updateByExample(@Param("record") ProductParams record, @Param("example") ProductParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PARAMS
     *
     * @mbg.generated Wed Sep 08 16:48:37 MSK 2021
     */
    int updateByPrimaryKeySelective(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_PARAMS
     *
     * @mbg.generated Wed Sep 08 16:48:37 MSK 2021
     */
    int updateByPrimaryKey(ProductParams record);
}